INSERT INTO corso (tipo) VALUES
("Programmazione"),
("Sicurezza"),
("Cloud"),
("Internet Of Things"),
("Intelligenza Artificiale"),
("Hardware"),
("Basi del computer"),
("Cultura dell'informatica");

INSERT INTO difficolta (diff) VALUES
("Facile"),
("Medio"),
("Difficile");

INSERT INTO domanda (domanda,fk_corso,difficoltaDomanda) VALUES
("Che significa l’acronimo CSS?","Programmazione","Facile"),
("Che significa l’acronimo HTML?","Programmazione","Facile"),
("Che significa l’acronimo JS?","Programmazione","Facile"),
("Che significa l’acronimo SQL?","Programmazione","Facile"),
("La differenza tra SQL e mySQL","Programmazione","Facile"),
("Che cos’è una Query string?","Programmazione","Facile"),
("Cos’è un puntatore?","Programmazione","Facile"),
("Differenze tra GET e POST","Programmazione","Facile"),
("In quali campi viene utilizzato Python?","Programmazione", "Facile"),
("Che cos’è Dev-C++?","Programmazione","Facile"),
("Che cos’è un IDE?","Programmazione","Facile"),
("La differenza tra un IDE ed un editor di testo?","Programmazione","Facile"),
("Cosa fa il comando 'printf()' in C?","Programmazione","Facile"),
("Come si conclude un comando in C?","Programmazione","Facile"),
("Che cos’è una libreria?","Programmazione","Facile");

INSERT INTO domanda (domanda,fk_corso,difficoltaDomanda) VALUES
("Come si stampa una stringa su Java?","Programmazione","Medio"),
("Quali parentesi si usano per la dichiarazione di un vettore in C?","Programmazione","Medio"),
("Come si dichiara una funzione in JavaScript?","Programmazione","Medio"),
("Che cos’è la classe 'Object' su Java?","Programmazione","Medio"),
("Che cosa sono i canvas su java?","Programmazione","Medio"),
("Che cosa sono i vettori paralleli?","Programmazione","Medio"),
("Qual è la differenza tra 'public' e 'private' in Java?","Programmazione","Medio"),
("cos’è il legame dinamico in java?","Programmazione","Medio"),
("Come si traduce il 'finché'  in C?","Programmazione","Medio"),
("Quale tra questi non è un ciclo 'for' corretto in C?","Programmazione","Medio"),
("Che cos’è una funzione 'void' in C?","Programmazione","Medio"),
("Che cos’è una webstring.h?","Programmazione","Medio"),
("Come si crea una tabella in SQL?","Programmazione","Medio"),
("Che cosa fa il comando 'select' in SQL?","Programmazione","Medio"),
("Di quale linguaggio appartiene il comando 'echo'?","Programmazione","Medio");

INSERT INTO domanda (domanda,fk_corso,difficoltaDomanda) VALUES
("Quale comando tra questi è sbagliato?","Programmazione","Difficile"),
("Quali tra questi comandi addEventListener è sbagliato?","Programmazione","Difficile"),
("Quali tra queste funzioni non implementa niente?","Programmazione","Difficile"),
("Quale tra questi comandi non è un comando java?","Programmazione","Difficile"),
("Cosa serve il comando 'integer'?","Programmazione","Difficile"),
("Cosa serve il comando position relative in HTML?","Programmazione","Difficile"),
("Cosa serve la manipolazione dei buffer in C?","Programmazione","Difficile"),
("A che cosa serve l'utilizzo di 'pipe()' in C?","Programmazione","Difficile"),
("Cosa sono le classi wrapper in Java?","Programmazione","Difficile"),
("A che cosa serve la libreria cv2 in python","Programmazione","Difficile"),
("A che cosa serve la libreria Tensor Flow?","Programmazione","Difficile"),
("Le differenze tra struct e union in C","Programmazione","Difficile"),
("Perché usare la funzione system()? Cosa cambia dal mettere solo return 0?","Programmazione","Difficile"),
("Quali tra questi linguaggi non è di programmazione?","Programmazione","Difficile"),
("Cosa serve per poter avviare Java nella macchina?","Programmazione","Difficile");

INSERT INTO domanda (domanda,fk_corso,difficoltaDomanda) VALUES
("A cosa serve la modalità incognito?","Sicurezza","Facile"),
("Che cos’è un antivirus?","Sicurezza","Facile"),
("Che cos’è una VPN?","Sicurezza","Facile"),
("Che cos’è un firewall?","Sicurezza","Facile"),
("Che cosa si intende per 'fishing'?","Sicurezza","Facile"),
("Che cosa si intende per 'spamming'?","Sicurezza","Facile"),
("Quali tra queste distribuzioni ha come base d’utilizzo una serie di programmi orientati al pentesting?","Sicurezza","Facile"),
("Cos’è il pentesting e perché è importante?","Sicurezza","Facile"),
("Chi è Kevin Mitnick?","Sicurezza","Facile"),
("Differenza tra client e server?","Sicurezza","Facile"),
("Quale tra queste architetture di rete viene utilizzata per le reti torrent?","Sicurezza","Facile"),
("Cosa significa CCCAM?","Sicurezza","Facile"),
("Perché non conviene utilizzare una tecnologia senza fili (Bluetooth, Wi-Fi, NFC…)?","Sicurezza","Facile"),
("Il Jammer è utile per…","Sicurezza","Facile"),
("Cos’è 'SQL Injection'?","Sicurezza","Facile");

INSERT INTO domanda (domanda,fk_corso,difficoltaDomanda) VALUES
("A cosa viene utilizzato il Port Mapping?","Sicurezza","Medio"),
("Quali tra questi software è utile per lo sniffing?","Sicurezza","Medio"),
("Cos’è un exploit in sicurezza informatica?","Sicurezza","Medio"),
("Quali sono gli strumenti per fare pentesting in locale tra questi?","Sicurezza","Medio"),
("Esiste anche un sito per fare pentesting, come si chiama?","Sicurezza","Medio"),
("In cosa consiste il Social Engineering?","Sicurezza","Medio"),
("In cosa consiste il Man in the Middle?","Sicurezza","Medio"),
("Quali tra questi attacchi è utilizzato per indovinare le password?","Sicurezza","Medio"),
("Quali tra questi protocolli è consigliato utilizzare nella propria rete?","Sicurezza","Medio"),
("Cos’è la Rubber Ducky?","Sicurezza","Medio"),
("Cos’è l’ALFA Network?","Sicurezza","Medio"),
("Differenza tra Trojan, Virus, Ransomware, Worm","Sicurezza","Medio"),
("Quali sono i gradi di malware?","Sicurezza","Medio"),
("In cosa consiste l’USB Killer?","Sicurezza","Medio"),
("Cos’è il Denial of Service? Qual è la differenza tra Denial of Service e Distributed Denial of Service?","Sicurezza","Medio");

INSERT INTO domanda (domanda,fk_corso,difficoltaDomanda) VALUES
("Cos’è il defacing di una pagina web?","Sicurezza","Difficile"),
("Chi è uno degli autori di Parrot OS?","Sicurezza","Difficile"),
("Cos’è un payload?","Sicurezza","Difficile"),
("In cosa consiste il tunneling con SOCKS?","Sicurezza","Difficile"),
("In cosa consiste il tunneling con SSH?","Sicurezza","Difficile"),
("In cosa consiste l’attacco watering hole?","Sicurezza","Difficile"),
("In cosa consiste il pharming?","Sicurezza","Difficile"),
("In cosa consiste il farmjacking?","Sicurezza","Difficile"),
("In cosa consiste il mishing?","Sicurezza","Difficile"),
("Cos’è Advanced Persistent Threat?","Sicurezza","Difficile"),
("Qual è la differenza tra IPTV e CCCAM?","Sicurezza","Difficile"),
("Come si effettua un MAC Spoofing?","Sicurezza","Difficile"),
("A cosa serve una backdoor?","Sicurezza","Difficile"),
("A cosa serve il progetto Cloud_enum?","Sicurezza","Difficile"),
("Quale tool tra questi viene utilizzato per fare Password Spraying?","Sicurezza","Difficile");

INSERT INTO domanda (domanda,fk_corso,difficoltaDomanda) VALUES
("Cos’è il cloud computing?","Cloud","Facile"),
("Quanti sono i principali servizi di cloud?","Cloud","Facile"),
("Quali sono i principali tipi di cloud?","Cloud","Facile"),
("Quali servizi offre un cloud?","Cloud","Facile"),
("In quali ambiti viene usato un cloud?","Cloud","Facile"),
("Quali sono le differenze tra cloud ibrido e privato?","Cloud","Facile"),
("Quali sono le differenze tra cloud privato e pubblico?","Cloud","Facile"),
("Su quali dispositivi si può utilizzare un cloud?","Cloud","Facile"),
("Il cloud è disponibile offline?","Cloud","Facile"),
("Che differenze ci sono tra cloud?","Cloud","Facile"),
("Cos’è la  'cloud security'?","Cloud","Facile"),
("Quali tipi di dati si possono salvare su un cloud?","Cloud","Facile"),
("Dove trovo il Cloud?","Cloud","Facile"),
("Come viene definito l’ambiente o l’architettura del cloud?","Cloud","Facile"),
("Da cosa deriva il nome 'cloud'?","Cloud","Facile");

INSERT INTO domanda (domanda,fk_corso,difficoltaDomanda) VALUES
("Cos’è Hive?","Cloud","Medio"),
("Quali sono i 3 principali vantaggi del cloud computing?","Cloud","Medio"),
("Cosa serve per utilizzare il cloud computing?","Cloud","Medio"),
("Come funziona mega?","Cloud","Medio"),
("Cos’è un data center?","Cloud","Medio"),
("Qual è  il principale data center di Apple?","Cloud","Medio"),
("Cos’è l’'infrastructure as a service'?","Cloud","Medio"),
("Cos’è il 'platform as a service'?","Cloud","Medio"),
("Cos’è il 'software as a service'?","Cloud","Medio"),
("Come viene anche chiamato il 'platform as a service'?","Cloud","Medio"),
("Cos’è il cloud privato?","Cloud","Medio"),
("Cos’è il cloud pubblico?","Cloud","Medio"),
("Cos’è il cloud ibrido?","Cloud","Medio"),
("Cos’è il multi-cloud?","Cloud","Medio"),
("A cosa serve Cloudera?","Cloud","Medio");

INSERT INTO domanda (domanda,fk_corso,difficoltaDomanda) VALUES
("Quali tra questi servizi non usa un'infrastruttura cloud?","Cloud","Difficile"),
("Dove vengono salvati fisicamente i dati che si trovano su un cloud?","Cloud","Difficile"),
("Cosa sono 'sistemi on-premise'?","Cloud","Difficile"),
("Quali sono i livelli di funzionamento dell’infrastruttura IaaS?","Cloud","Difficile"),
("Su quale architettura si appoggia l’Azure di Microsoft?","Cloud","Difficile"),
("Quali sono i livelli di funzionamento dell’infrastruttura PaaS?","Cloud","Difficile"),
("Quali sono i livelli di funzionamento dell’infrastruttura SaaS?","Cloud","Difficile"),
("Che differenza c’è tra Mainframe e Cloud?","Cloud","Difficile"),
("Cosa sono i server dedicati?","Cloud","Difficile"),
("Pro e contro tra Cloud-based e In-House servers?","Cloud","Difficile"),
("Cos’è una VPS?","Cloud","Difficile"),
("Cos’è una 'cloud migration'?","Cloud","Difficile"),
("Cos’è 'hadoop'?","Cloud","Difficile"),
("Cos'è il CSP?","Cloud","Difficile"),
("Differenze tra Cloudera e Spark","Cloud","Difficile");

INSERT INTO domanda (domanda,fk_corso,difficoltaDomanda) VALUES
("Dov’è non è stata implementata la tecnologia Bluetooth?","Internet of Things","Facile"),
("Cosa si intende per Internet of Things?","Internet of Things","Facile"),
("Cos’è Arduino?","Internet of Things","Facile"),
("Cos’è Raspberry Pi?","Internet of Things","Facile"),
("Cos’è il sonar?","Internet of Things","Facile"),
("Di cosa si tratta la smart-city?","Internet of Things","Facile"),
("Di cosa si tratta la smart-grid","Internet of Things","Facile"),
("Quale tra questi ambienti non viene utilizzata l’IoT?","Internet of Things","Facile"),
("Quali tra questi sono esempi di sicurezza domotica?","Internet of Things","Facile"),
("Indica tra questi esempi le funzioni di impianto elettrico intelligente","Internet of Things","Facile"),
("Indica tra questi esempi le funzioni di impianto climatizzazione intelligente","Internet of Things","Facile"),
("Indica tra questi esempi le funzioni di impianto automazione intelligente","Internet of Things","Facile"),
("Cosa si intende per Smart Agriculture?","Internet of Things","Facile"),
("Cos’è Moocall?","Internet of Things","Facile"),
("Cos’è il Wireless Sensor Network?","Internet of Things","Facile");

INSERT INTO domanda (domanda,fk_corso,difficoltaDomanda) VALUES
("A cosa serve 'RFID' nell’IoT?","Internet of Things","Medio"),
("Quale tra queste definizioni fa riferimento al 'Vehicle-To-Everything'?","Internet of Things","Medio"),
("Cos’è il Bluelink della Hyundai?","Internet of Things","Medio"),
("Cos’è il Virtual Cockpit?","Internet of Things","Medio"),
("Qual è il significato dell’acronimo 'ADAS'?","Internet of Things","Medio"),
("Cos’è il digital twin?","Internet of Things","Medio"),
("Di cosa si tratta il Machine2Machine?","Internet of Things","Medio"),
("Cos’è lo SCADA?","Internet of Things","Medio"),
("Che architettura hardware e software utilizza Arduino?","Internet of Things","Medio"),
("Tra queste opzioni c’è un’azienda che si occupa del settore sanitario con l’uso dell’IoT, qual è?","Internet of Things","Medio"),
("Quali sono le caratteristiche della smart-city?","Internet of Things","Medio"),
("A cosa servono le smart-city?","Internet of Things","Medio"),
("Quali delle città ha implementato le smart-city?","Internet of Things","Medio"),
("Che problemi si potrebbero riscontrare nell’IoT?","Internet of Things","Medio"),
("Quali sono i vantaggi dell’applicazione dell’IoT nella medicina?","Internet of Things","Medio");

INSERT INTO domanda (domanda,fk_corso,difficoltaDomanda) VALUES
("Come funziona una smart card?","Internet of Things","Difficile"),
("Cos’è l’edge computing e come viene applicata la tecnologia dell’IoT in quell’ambito?","Internet of Things","Difficile"),
("Come funziona il movimento dei droni?","Internet of Things","Difficile"),
("Cos’è il Red Hat OpenShift?","Internet of Things","Difficile"),
("Cosa significa dell’IIoT?","Internet of Things","Difficile"),
("Come funziona l’automazione dell’IIoT?","Internet of Things","Difficile"),
("Cosa Industry 4.0?","Internet of Things","Difficile"),
("La quarta rivoluzione industriale?","Internet of Things","Difficile"),
("Come funziona feed-forward?","Internet of Things","Difficile"),
("Cosa tratta la rete neurale spiking?","Internet of Things","Difficile"),
("Quali tra questi è un modello di rete neurale artificiale?","Internet of Things","Difficile"),
("Quale tra questi è un algoritmo di rete neurale a base radiale?","Internet of Things","Difficile"),
("Quale algoritmo tra questi viene utilizzato per lo spam filtering?","Internet of Things","Difficile"),
("Quale tra queste tecnologie bisognerebbe utilizzare per il riconoscimento vocale?","Internet of Things","Difficile"),
("Cos’è AlphaZero?","Internet of Things","Difficile");

INSERT INTO domanda (domanda,fk_corso,difficoltaDomanda) VALUES
("Che cos’è un intelligenza artificiale?","Intelligenza Artificiale","Facile"),
("Che cos’è un assistente vocale?","Intelligenza Artificiale","Facile"),
("Che cosa può fare un assistente vocale?","Intelligenza Artificiale","Facile"),
("Quanti livelli ha l'intelligenza artificiale?","Intelligenza Artificiale","Facile"),
("Quali sono i due tipi di IA?","Intelligenza Artificiale","Facile"),
("Quali sono i sottoinsiemi dell’intelligenza artificiale tra queste risposte?","Intelligenza Artificiale","Facile"),
("Chi ha coniato il termine intelligenza artificiale?","Intelligenza Artificiale","Facile"),
("Cosa si intende per intelligenza artificiale forte?","Intelligenza Artificiale","Facile"),
("In che decennio nacque l'Intelligenza Artificiale?","Intelligenza Artificiale","Facile"),
("Quali sono gli svantaggi dell'intelligenza artificiale?","Intelligenza Artificiale","Facile"),
("In che settori viene utilizzata oggi l'intelligenza artificiale?","Intelligenza Artificiale","Facile"),
("Che cosa si intende per deep learning?","Intelligenza Artificiale","Facile"),
("Che cosa si intende per back-propagation?","Intelligenza Artificiale","Facile"),
("La robotica è direttamente associata all'intelligenza artificiale?","Intelligenza Artificiale","Facile"),
("Indica l’ordine di funzionamento dell’intelligenza artificiale","Intelligenza Artificiale","Facile");

INSERT INTO domanda (domanda,fk_corso,difficoltaDomanda) VALUES
("In cosa consiste il principio di Asilomar?","Intelligenza Artificiale","Medio"),
("In cosa consiste la macchina di Turing?","Intelligenza Artificiale","Medio"),
("Cos’è il grid computing?","Intelligenza Artificiale","Medio"),
("Perché si parla di IA-completo?","Intelligenza Artificiale","Medio"),
("Cos’è Watson?","Intelligenza Artificiale","Medio"),
("Qual è il nome dell’intelligenza artificiale utilizzata dalla Tesla per l’autoguida?","Intelligenza Artificiale","Medio"),
("Quando nacque e dove nacque l’intelligenza artificiale?","Intelligenza Artificiale","Medio"),
("Chi è il padre dell’intelligenza artificiale?","Intelligenza Artificiale","Medio"),
("In cosa consiste la Rete neurale artificiale?","Intelligenza Artificiale","Medio"),
("In cosa consiste Deep Blue?","Intelligenza Artificiale","Medio"),
("In cosa consiste Google DeepMind?","Intelligenza Artificiale","Medio"),
("Cosa tratta l’algoritmo genetico?","Intelligenza Artificiale","Medio"),
("Differenza tra Machine Learning, Deep Learning e Intelligenza Artificiale?","Intelligenza Artificiale","Medio"),
("Cosa tratta l’algoritmo evolutivo?","Intelligenza Artificiale","Medio"),
("In cosa si tratta la neuroevoluzione?","Intelligenza Artificiale","Medio");

INSERT INTO domanda (domanda,fk_corso,difficoltaDomanda) VALUES
("In cosa consiste 'Black-Box AI'?","Intelligenza Artificiale","Difficile"),
("Cos’è Acovea?","Intelligenza Artificiale","Difficile"),
("In cosa consiste Particle Swarm Optimization?","Intelligenza Artificiale","Difficile"),
("Cos’è il concetto di crossover dell'algoritmo genetico?","Intelligenza Artificiale","Difficile"),
("Come funziona l’Auto-Pilot di Tesla?","Intelligenza Artificiale","Difficile"),
("Cos’è l’EDLUT?","Intelligenza Artificiale","Difficile"),
("Come funziona l’EDLUT?","Intelligenza Artificiale","Difficile"),
("Come funziona feed-forward?","Intelligenza Artificiale","Difficile"),
("Cosa tratta la rete neurale spiking?","Intelligenza Artificiale","Difficile"),
("Quali tra questi è un modello di rete neurale artificiale?","Intelligenza Artificiale","Difficile"),
("Quale tra questi è un algoritmo di rete neurale a base radiale?","Intelligenza Artificiale","Difficile"),
("Quale algoritmo tra questi viene utilizzato per lo spam filtering?","Intelligenza Artificiale","Difficile"),
("Quale tra queste tecnologie bisognerebbe utilizzare per il riconoscimento vocale?","Intelligenza Artificiale","Difficile"),
("Quali tra questi algoritmi si utilizza per la traduzione o language translation?","Intelligenza Artificiale","Difficile"),
("Cos’è AlphaZero?","Intelligenza Artificiale","Difficile");

INSERT INTO domanda (domanda,fk_corso,difficoltaDomanda) VALUES
("Che cos’è la ROM?","Hardware","Facile"),
("Come funziona un mouse?","Hardware","Facile"),
("Quali tra questi non è un dispositivo di input?","Hardware","Facile"),
("Quali tra questi non è un dispositivo di output?","Hardware","Facile"),
("Che cos’è il case?","Hardware","Facile"),
("Cosa deve aver un computer per leggere un disco?","Hardware","Facile"),
("Perchè se colleghi le cuffie all’AUX non funziona il microfono?","Hardware","Facile"),
("Qual è la differenza tra tastiera a membrana e meccanica?","Hardware","Facile"),
("Che vantaggi ha una tastiera meccanica?","Hardware","Facile"),
("Che vantaggi ha una tastiera a membrana?","Hardware","Facile"),
("Come si chiamano i 'puntini' sotto il processore?","Hardware","Facile"),
("Di quali materiali è fatta la scheda madre?","Hardware","Facile"),
("Di che materiale è fatto il processore?","Hardware","Facile"),
("Che cosa sono i DPI?","Hardware","Facile"),
("Quale funzione ha la ventola?","Hardware","Facile");

INSERT INTO domanda (domanda,fk_corso,difficoltaDomanda) VALUES
("Qual è il componente più costoso di un PC da gaming?","Hardware","Medio"),
("Che cos’è il profilo XMP?","Hardware","Medio"),
("Quanto costa  un masterizzatore CD?","Hardware","Medio"),
("Quali tra queste CPU è più costose?","Hardware","Medio"),
("Quali tra queste GPU è più costose?","Hardware","Medio"),
("Qual è la differenza tra AMD ed NVIDIA?","Hardware","Medio"),
("Quale tra queste schede madri non è compatibile con il processore Ryzen 7 3800x?","Hardware","Medio"),
("Che differenza c’è tra multi-core e single core?","Hardware","Medio"),
("Quali tra questi processori girano meglio in multi-core?","Hardware","Medio"),
("A cosa serve il silicio?","Hardware","Medio"),
("Da dove prendono il silicio le grandi aziende?","Hardware","Medio"),
("Come mai le schede video sono in aumento di prezzo dal 2020?","Hardware","Medio"),
("Perché ora le grandi aziende sono a corto di Chip?","Hardware","Medio"),
("Perché è importante una buona ventilazione?","Hardware","Medio"),
("Che differenza c’è tra i dissipatori AIO e quelli ad aria?","Hardware","Medio");

INSERT INTO domanda (domanda,fk_corso,difficoltaDomanda) VALUES
("Quale tra questi processori ha il socket LGA 2066?","Hardware","Difficile"),
("Quale tra questi processori ha più di 25 MB di cache?","Hardware","Difficile"),
("Quale tra questi processori ha più di 150 watt di potenza?","Hardware","Difficile"),
("Qual è la differenza tra un alimentatore modulare e uno non?","Hardware","Difficile"),
("Quale tra queste schede madri non supporta i 3200 MHz di ram?","Hardware","Difficile"),
("Quanta ram serve per avviare Microsoft Flight simulator?","Hardware","Difficile"),
("Qual è la differenza tra VRAM e NVRAM?","Hardware","Difficile"),
("Per una configurazione con: I9 11900k, 32gb ram, 3080 ti, z590 quale PSU serve per farla funzionare correttamente?","Hardware","Difficile"),
("Che differenza c'è tra una PSU Bronze, Silver, Gold e Platinum?","Hardware","Difficile"),
("Qual è il vantaggio delle RAM DDR5? E perchè sono meglio delle precedenti DDR4?","Hardware","Difficile"),
("Che funzione ha il V-SYNC?","Hardware","Difficile"),
("Che differenza ce tra freeSync e G-sync?","Hardware","Difficile"),
("Quali tra questi switch sono più veloci?","Hardware","Difficile"),
("Che differenza c’è tra un monitor LCD e Amoled?","Hardware","Difficile"),
("Che funzioni hanno i MINI-LED della nuova gamma di Samsung?","Hardware","Difficile");

INSERT INTO domanda (domanda,fk_corso,difficoltaDomanda) VALUES
("Come si usa la funzione 'copia' da tastiera?","Basi del Computer","Facile"),
("Come si usa la funzione 'incolla' da tastiera?","Basi del Computer","Facile"),
("Che cos’è un’icona?","Basi del Computer","Facile"),
("Che cos’è più grande?","Basi del Computer","Facile"),
("Come si possono trasferire immagini da telefono a pc?","Basi del Computer","Facile"),
("A cosa serve il tasto Windows?","Basi del Computer","Facile"),
("Come si scrive il carattere 'È'?","Basi del Computer","Facile"),
("Come si stampa un file?","Basi del Computer","Facile"),
("Che cos’è una 'scorciatoia da tastiera'?","Basi del Computer","Facile"),
("Cosa succede se metti un programma nel cestino?","Basi del Computer","Facile"),
("Che proprietà ha il formato PDF?","Basi del Computer","Facile"),
("Che significa il formato txt?","Basi del Computer","Facile"),
("Che significa il formato ppt?","Basi del Computer","Facile"),
("Quale tra i seguenti dispositivi di memoria ha la capacità più alta?","Basi del Computer","Facile"),
("Come si fa ad installare Windows su una macchina appena montata?","Basi del Computer","Facile");

INSERT INTO domanda (domanda,fk_corso,difficoltaDomanda) VALUES
("Che cos’è una macchina virtuale?","Basi del Computer","Medio"),
("Che differenza c'è tra HTTP e HTTPS?","Basi del Computer","Medio"),
("Dove si usa il protocollo HTTP?","Basi del Computer","Medio"),
("Che cos’è un collegamento ipertestuale?","Basi del Computer","Medio"),
("Quanto è grande uno Yottabyte (in byte)?","Basi del Computer","Medio"),
("Che cosa fa il kernel?","Basi del Computer","Medio"),
("Cos’è un hypervisor?","Basi del Computer","Medio"),
("Cosa si intende per 'struttura ad albero' in ambito di salvataggio dati?","Basi del Computer","Medio"),
("Quanti caratteri diversi possono essere rappresentati con il codice ASCII?","Basi del Computer","Medio"),
("Dove sono contenuti i dati che vanno persi quando si spegne il pc?","Basi del Computer","Medio"),
("Che funzione svolge la ALU?","Basi del Computer","Medio"),
("Che cosa si intende per 'linguaggio ad alto livello'?","Basi del Computer","Medio"),
("Cosa sono i registri di sistema?","Basi del Computer","Medio"),
("Qual è la caratteristica principale di un programma open source?","Basi del Computer","Medio"),
("Cosa sono i Java Applets?","Basi del Computer","Medio");

INSERT INTO domanda (domanda,fk_corso,difficoltaDomanda) VALUES
("Come si ripristina la password irrecuperabile del BIOS / UEFI nei computer?","Basi del Computer","Difficile"),
("Per cosa sta l’acronimo RDP?","Basi del Computer","Difficile"),
("Cos’è un settore di un hard disk?","Basi del Computer","Difficile"),
("Qual è l’utilizzo dell’OU in Active Directory?","Basi del Computer","Difficile"),
("Per cosa sta l’acronimo MDM?","Basi del Computer","Difficile"),
("IEEE 1394 è conosciuto anche come?","Basi del Computer","Difficile"),
("Differenza tra Telnet e SSH?","Basi del Computer","Difficile"),
("A cosa sono legati il CUDA e il PhysX?","Basi del Computer","Difficile"),
("Cosa sono GNOME e KDE?","Basi del Computer","Difficile"),
("Quale tra queste non è un VMM?","Basi del Computer","Difficile"),
("Cos’è il Blue Screen of Death?","Basi del Computer","Difficile"),
("Qual è il nome del processo che ha come valore PID 1 in Linux?","Basi del Computer","Difficile"),
("Qual è l’output di un input con valori 1,1 con 2 nella porta logica XOR?","Basi del Computer","Difficile"),
("Quale tra questi nomi di processi avvia le impostazioni del ODBC?","Basi del Computer","Difficile"),
("Quale tra queste non è un Version Control System?","Basi del Computer","Difficile");

INSERT INTO domanda (domanda,fk_corso,difficoltaDomanda) VALUES
("Chi è il fondatore di Google?","Cultura dell'Informatica","Facile"),
("Cosa significa PCI?","Cultura dell'Informatica","Facile"),
("Cos’è WannaCry?","Cultura dell'Informatica","Facile"),
("Cos’è Jigsaw?","Cultura dell'Informatica","Facile"),
("Chi è il co-fondatore della Apple?","Cultura dell'Informatica","Facile"),
("Chi è Sean Parker?","Cultura dell'Informatica","Facile"),
("Cos’è CryptoLocker?","Cultura dell'Informatica","Facile"),
("Cos’è Bitcoin?","Cultura dell'Informatica","Facile"),
("Cos’è una Blockchain?","Cultura dell'Informatica","Facile"),
("Cos’è il kernel?","Cultura dell'Informatica","Facile"),
("Perché è importante il SEO?","Cultura dell'Informatica","Facile"),
("Per quale motivo venne progettato il layout delle tastiere QWERTY? Qual è il beneficio?","Cultura dell'Informatica","Facile"),
("Qual è il nome precedente di Java?","Cultura dell'Informatica","Facile"),
("Chi inventò il primo computer?","Cultura dell'Informatica","Facile"),
("Chi sono i padri del kernel GNU/Linux?","Cultura dell'Informatica","Facile");

INSERT INTO domanda (domanda,fk_corso,difficoltaDomanda) VALUES
("Per cosa si usa Citrix?","Cultura dell'Informatica","Medio"),
("Cosa significa COBOL?","Cultura dell'Informatica","Medio"),
("Che cos’è un chipset?","Cultura dell'Informatica","Medio"),
("Da dove potresti mappare un'unità di rete in windows?","Cultura dell'Informatica","Medio"),
("Cosa significa O in CMOS?","Cultura dell'Informatica","Medio"),
("Quale azienda non ha mai prodotto pc?","Cultura dell'Informatica","Medio"),
("Nella gestione dei computer windows a cosa serve ODBC?","Cultura dell'Informatica","Medio"),
("Cosa viene usato per suddividere i valori in un file csv?","Cultura dell'Informatica","Medio"),
("Cos’è il DMA?","Cultura dell'Informatica","Medio"),
("A cosa serve il DHCP?","Cultura dell'Informatica","Medio"),
("Per  cosa viene usato il firewire?","Cultura dell'Informatica","Medio"),
("In C++ per cosa è usato il simbolo '!='?","Cultura dell'Informatica","Medio"),
("Quale dei seguenti non è un linguaggio di programmazione?","Cultura dell'Informatica","Medio"),
("Cos’è un settore disco su un disco rigido?","Cultura dell'Informatica","Medio"),
("Cosa significa SONET?","Cultura dell'Informatica","Medio");

INSERT INTO domanda (domanda,fk_corso,difficoltaDomanda) VALUES
("Cosa apparirebbe se digitassi 'cal' in linux bash?","Cultura dell'Informatica","Difficile"),
("Qual è il primo dei seguenti sistemi operativi che supporta nativamente il comando TRIM per le unità SATA allo stato solido?","Cultura dell'Informatica","Difficile"),
("Qual è la differenza tra gli hypervisor di tipo 1 e 2?","Cultura dell'Informatica","Difficile"),
("A cosa serve il comando 'cp' in linux bash?","Cultura dell'Informatica","Difficile"),
("Quale delle seguenti funzioni ha una funzione smagnetizzante?","Cultura dell'Informatica","Difficile"),
("Qual è la causa più probabile di un overflow dello stack?","Cultura dell'Informatica","Difficile"),
("Quali sono le architetture del kernel GNU/Linux?","Cultura dell'Informatica","Difficile"),
("Su quale kernel sono basati GNU/Linux, macOS, Windows e altri?","Cultura dell'Informatica","Difficile"),
("Quali sono le shell più utilizzate nelle architetture basate sul kernel GNU/Linux?","Cultura dell'Informatica","Difficile"),
("Per cosa venne sviluppato originalmente FORTRAN?","Cultura dell'Informatica","Difficile"),
("Converti 1011B (binario) in esadecimale.","Cultura dell'Informatica","Difficile"),
("Quale tipo di struttura dati è una queue?","Cultura dell'Informatica","Difficile"),
("Quale tra questi non è un software per il web server?","Cultura dell'Informatica","Difficile"),
("Per cosa sta la D nell’acronimo CIDR?","Cultura dell'Informatica","Difficile"),
("Quale tra queste è un Distributed Version Control System?","Cultura dell'Informatica","Difficile");

